workflows:
  flutter-android-apk:
    name: Flutter Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.47.2
      # groups 字段已删除，因为目前不需要
    scripts:
      - name: 设置 Flutter SDK 路径
        script: | 
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: 获取 Flutter 依赖
        script: | 
          flutter pub get
      - name: 构建 Debug APK
        script: | 
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk